import type { Metadata } from "next";
import { Rubik, Handlee } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { UserContextProvider } from "./context/user.context";

const rubik = Rubik({
  subsets: ["latin"],
});

const handlee = Handlee({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <UserContextProvider>
        <body>
          {children}
        </body>
      </UserContextProvider>
    </html>
  );
}
